# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: 'Choose browser to run Tests'
        default: 'edge'
        options:
          - 'edge'
          - 'chrome'
          
      environment:
        type: choice
        description: 'Choose environment to run Tests'
        default: 'stage'
        options:
          - 'dev'
          - 'stage'
            
  push:
    branches: [ "CucumberBDD" ]
    
  pull_request:
    branches: [ "CucumberBDD" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Run Tests
      run: >
         mvn clean test
         -Dbrowser=${{inputs.browser || 'edge'}}
         -Denv=${{inputs.environment || 'stage'}} 
    
    - name: Upload Screenshots
      uses: actions/upload-artifact@v3
      with:
        name: Screenshots
        path: screenshots
      if: always()
